// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: nat-chan/runtime-accel/runtime_accel.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "nat_chan.runtime_accel";

/** List the instance ids of all runtime-accel input processors in the build. */
export interface ListInstancesRequest {
}

export interface ListInstancesResponse {
  /** Devicetree `instance-id` of each processor instance (e.g. "pointer"). */
  ids: string[];
}

/** Read the currently active (RAM) curve of one instance. */
export interface GetCurveRequest {
  instanceId: string;
}

export interface CurveResponse {
  instanceId: string;
  /**
   * Interleaved [s0, f0, s1, f1, ...], already sanitized.
   * sint32 (zigzag): a plain int32 would cost 10 bytes per negative value
   * and blow the CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE budget.
   */
  points: number[];
}

/**
 * Replace the curve of one instance. persist=false stages the curve in RAM
 * only (custom-settings MEMORY write); persist=true also saves it to flash.
 */
export interface SetCurveRequest {
  instanceId: string;
  /** see CurveResponse.points */
  points: number[];
  persist: boolean;
}

export interface AckResponse {
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  listInstances?: ListInstancesRequest | undefined;
  getCurve?: GetCurveRequest | undefined;
  setCurve?: SetCurveRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  instances?: ListInstancesResponse | undefined;
  curve?: CurveResponse | undefined;
  ack?: AckResponse | undefined;
}

function createBaseListInstancesRequest(): ListInstancesRequest {
  return {};
}

export const ListInstancesRequest: MessageFns<ListInstancesRequest> = {
  encode(_: ListInstancesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInstancesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInstancesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListInstancesRequest>): ListInstancesRequest {
    return ListInstancesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListInstancesRequest>): ListInstancesRequest {
    const message = createBaseListInstancesRequest();
    return message;
  },
};

function createBaseListInstancesResponse(): ListInstancesResponse {
  return { ids: [] };
}

export const ListInstancesResponse: MessageFns<ListInstancesResponse> = {
  encode(message: ListInstancesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInstancesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInstancesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListInstancesResponse>): ListInstancesResponse {
    return ListInstancesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListInstancesResponse>): ListInstancesResponse {
    const message = createBaseListInstancesResponse();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetCurveRequest(): GetCurveRequest {
  return { instanceId: "" };
}

export const GetCurveRequest: MessageFns<GetCurveRequest> = {
  encode(message: GetCurveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceId !== "") {
      writer.uint32(10).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCurveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCurveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetCurveRequest>): GetCurveRequest {
    return GetCurveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetCurveRequest>): GetCurveRequest {
    const message = createBaseGetCurveRequest();
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseCurveResponse(): CurveResponse {
  return { instanceId: "", points: [] };
}

export const CurveResponse: MessageFns<CurveResponse> = {
  encode(message: CurveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceId !== "") {
      writer.uint32(10).string(message.instanceId);
    }
    writer.uint32(18).fork();
    for (const v of message.points) {
      writer.sint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CurveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.points.push(reader.sint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.points.push(reader.sint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CurveResponse>): CurveResponse {
    return CurveResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CurveResponse>): CurveResponse {
    const message = createBaseCurveResponse();
    message.instanceId = object.instanceId ?? "";
    message.points = object.points?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetCurveRequest(): SetCurveRequest {
  return { instanceId: "", points: [], persist: false };
}

export const SetCurveRequest: MessageFns<SetCurveRequest> = {
  encode(message: SetCurveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceId !== "") {
      writer.uint32(10).string(message.instanceId);
    }
    writer.uint32(18).fork();
    for (const v of message.points) {
      writer.sint32(v);
    }
    writer.join();
    if (message.persist !== false) {
      writer.uint32(24).bool(message.persist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetCurveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetCurveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.points.push(reader.sint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.points.push(reader.sint32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.persist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetCurveRequest>): SetCurveRequest {
    return SetCurveRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetCurveRequest>): SetCurveRequest {
    const message = createBaseSetCurveRequest();
    message.instanceId = object.instanceId ?? "";
    message.points = object.points?.map((e) => e) || [];
    message.persist = object.persist ?? false;
    return message;
  },
};

function createBaseAckResponse(): AckResponse {
  return {};
}

export const AckResponse: MessageFns<AckResponse> = {
  encode(_: AckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AckResponse>): AckResponse {
    return AckResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<AckResponse>): AckResponse {
    const message = createBaseAckResponse();
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { listInstances: undefined, getCurve: undefined, setCurve: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.listInstances !== undefined) {
      ListInstancesRequest.encode(message.listInstances, writer.uint32(10).fork()).join();
    }
    if (message.getCurve !== undefined) {
      GetCurveRequest.encode(message.getCurve, writer.uint32(18).fork()).join();
    }
    if (message.setCurve !== undefined) {
      SetCurveRequest.encode(message.setCurve, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.listInstances = ListInstancesRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getCurve = GetCurveRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setCurve = SetCurveRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.listInstances = (object.listInstances !== undefined && object.listInstances !== null)
      ? ListInstancesRequest.fromPartial(object.listInstances)
      : undefined;
    message.getCurve = (object.getCurve !== undefined && object.getCurve !== null)
      ? GetCurveRequest.fromPartial(object.getCurve)
      : undefined;
    message.setCurve = (object.setCurve !== undefined && object.setCurve !== null)
      ? SetCurveRequest.fromPartial(object.setCurve)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, instances: undefined, curve: undefined, ack: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.instances !== undefined) {
      ListInstancesResponse.encode(message.instances, writer.uint32(18).fork()).join();
    }
    if (message.curve !== undefined) {
      CurveResponse.encode(message.curve, writer.uint32(26).fork()).join();
    }
    if (message.ack !== undefined) {
      AckResponse.encode(message.ack, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instances = ListInstancesResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.curve = CurveResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ack = AckResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.instances = (object.instances !== undefined && object.instances !== null)
      ? ListInstancesResponse.fromPartial(object.instances)
      : undefined;
    message.curve = (object.curve !== undefined && object.curve !== null)
      ? CurveResponse.fromPartial(object.curve)
      : undefined;
    message.ack = (object.ack !== undefined && object.ack !== null) ? AckResponse.fromPartial(object.ack) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
